version: '3.9'

services:
  web:
    build: .
    command: ./wait-for-db.sh python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: integrador
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

volumes:
  pgdata:
